name: firestore_jobs_api
description: My new Firestore package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.5
  fake_cloud_firestore: ^2.4.1+1
  flutter:
    sdk: flutter
  jobs_api:
    path: ../jobs_api
  mockito: ^5.3.2
 
dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
